### ISSUE TITLE
Need help how-to train Tesseract 

### ISSUE THREAD

**Issue by Akossimon** [tesseract-ocr/tesstrain#101]
Fraktur Tesseract OCR is what I am looking for,.... I installed VietOCR v5.5.2 and Tesseract 4.1.0 on my mac, and now I am trying to find help on how to train it better.... there are too many OCR errors... 

How would I go about training the software? Can anyone help?

I am a total retard, ...sadly,.... and I do not even know how I was able to install the two components so far..... and this training step is nowhere explained

Any help into the right direction would greatly be appreciated

**Comment by stweil** [comment]
I suggest to start with existing models for Fraktur, for example my [GT4HistOCR_2000000.traineddata](https://ub-backup.bib.uni-mannheim.de/~stweil/ocrd-train/data/GT4HistOCR_2000000.traineddata). See also https://github.com/tesseract-ocr/tessdata/issues/102 and the [Wiki](https://github.com/tesseract-ocr/tesstrain/wiki/GT4HistOCR).

**Comment by Akossimon** [comment]
where can i learn how to implement these ?

I use a Mac and  a GUI VietOCR right now...




On Oct 5, 2019, at 6:56 PM, Stefan Weil <notifications@github.com> wrote:

I suggest to start with existing models for Fraktur, for example my GT4HistOCR_2000000.traineddata <https://ub-backup.bib.uni-mannheim.de/~stweil/ocrd-train/data/GT4HistOCR_2000000.traineddata>. See also tesseract-ocr/tessdata#102 <https://github.com/tesseract-ocr/tessdata/issues/102> and the Wiki <https://github.com/tesseract-ocr/tesstrain/wiki/GT4HistOCR>.

**Comment by wrznr** [comment]
For a high-level overview on the training process, pls. refer to https://github.com/tesseract-ocr/tesseract/wiki/TrainingTesseract-4.00

To use the software provided in this repository, you should have a basic understanding of the training process and some skills with a Unix command line. VietOCR won't help you much. Sorry.
