### ISSUE TITLE
Correct way to interrupt training

### ISSUE THREAD

**Issue by mikylucky** [tesseract-ocr/tesstrain#103]
Which is the correct way to interrupt training?

**Comment by stweil** [comment]
There is no single way. Training stops automatically after `MAX_ITERATIONS` iterations, but you can stop it earlier by killing the training process (press CTRL-C, use `kill` command, ...). If you just want to suspend it and resume it later, CTRL-Z or `kill -STOP` can be used.

**Comment by mikylucky** [comment]
Thanks a lot!
