### ISSUE TITLE
How to read training performance log?

### ISSUE THREAD

**Issue by mikylucky** [tesseract-ocr/tesstrain#106]
Hi everyone! As per the title, I'm interested in understading how the performance of the model goes.

Can someone explain how to read the following log line?

```
At iteration 6914/8100/8140, Mean rms=7.015%, delta=21.517%, char train=122.218%, word train=96.4%, skip ratio=0.5%,  New worst char error = 122.218At iteration 6019, stage 0, Eval Char error rate=120.07764, Word error rate=100 wrote checkpoint.
```

Thank you!

**Comment by wrznr** [comment]
@mikylucky https://github.com/tesseract-ocr/tesseract/wiki/TrainingTesseract-4.00#iterations-and-checkpoints might also be relevant in this respect.

**Comment by mikylucky** [comment]
Hi @wrznr, thanks for the info!

I surely have empty lines in my training data, should I avoid that?

**Comment by mikylucky** [comment]
@wrznr removing empty lines solved the error > 100% problem

**Comment by wrznr** [comment]
Cool!
