### ISSUE TITLE
Which is the command to finetune from another traineddata?

### ISSUE THREAD

**Issue by mikylucky** [tesseract-ocr/tesstrain#107]
It's me again :)

I'm trying to finetune a pretrained model, but I cannot understand how to use cmd options to start from a previous traineddata.

Can you show me an example please?

**Comment by stweil** [comment]
See an [example](https://github.com/tesseract-ocr/tesstrain/wiki/GT4HistOCR#finetuning-based-on-scriptfraktur) for a training based on Script/Fraktur.traineddata.

**Comment by mikylucky** [comment]
Thanks @stweil ! I see that the parameter TESSDATA is not reported in the readme, should we add it?

**Comment by wrznr** [comment]
@mikylucky They are at least mentioned in the [README.md](https://github.com/tesseract-ocr/tesstrain/blob/master/README.md#train) file. Is that sufficient for you?

**Comment by mikylucky** [comment]
I've just noticed START_MODEL, sorry! But I really cant' find TESSDATA, I see only TESSDATA_REPO

**Comment by mikylucky** [comment]
@stweil it's still not clear to me what should I put in TESSDATA and START_MODEL: names or paths?

If paths: I understand I have to put the path to the traineddata file in TESSDATA, but I can't understand which path I should put in START_MODEL.

If names: which are the available options?

**Comment by stweil** [comment]
`Makefile` combines both values to find the traineddata file for starting the training: `$(TESSDATA)/$(START_MODEL).traineddata`. I suggest to use a name like for example `eng`, `deu`, `frk`, `Fraktur` or `Latin` for `START_MODEL`. Then copy the corresponding traineddata file to the `./usr/share/tessdata` directory, and setting `TESSDATA` is not needed.

**Comment by wrznr** [comment]
@mikylucky Did the explanation by @stweil help you to solve this issue?

**Comment by mikylucky** [comment]
@wrznr the training starts without errors, but I cannot really understand if it is finetuning or starting from scratch. How would you check that?

**Comment by wrznr** [comment]
As soon as you set a `START_MODEL`, training can be called finetuning of this existing model. You can search for the parameter `--continue_from` of the command `lstmtraining` in the terminal output for confirmation.

**Comment by mikylucky** [comment]
Yeah, but the thing is that if I use fake values for `START_MODEL` and `TESSDATA`, the script doesn't throw any error.

Following your advice, I looked for `--continue_from` parameter and it gives me a path to an `.lstm` file that I don't have.

Where should I find the .lstm file related to the model I'm using? I'm trying to base my finetuning on the `digits.traineddata` from [here](https://github.com/Shreeshrii/tessdata_shreetest).
