### ISSUE TITLE
Add a variable to control Tesseract's dpi parameter

### ISSUE THREAD

**Issue by wrznr** [tesseract-ocr/tesstrain#108]
Tesseract has the parameter `--dpi` for images which lack DPI information in their meta data. To avoid that Tesseract hast to guess the image's DPI and to suppress the subsequent warning, it might be useful to add a corresponding variable to the Makefile.

**Comment by stweil** [comment]
You can (mis-)use the existing `PSM` parameter. :-)

Example: `PSM=6 --dpi 300`

I think that the image resolution is not used here, so Tesseract issues an unnecessary warning that should be removed.

**Comment by wrznr** [comment]
So, I can safely ignore the warning (and the often incorrect estimation of an image's DPI)?

**Comment by stweil** [comment]
Yes for training. No for recognition. Hm, while writing this answer I just think again about training: it runs recognition on the evaluation set. Up to now I only examined the initial training phase. The evaluation phase still needs a closer look whether it uses the DPI information.

**Comment by stweil** [comment]
I forgot something. Training and evaluation both use lstmf files (which include the image and the text). According to my tests, those lstm files don't change when I pass different `--dpi` arguments. That implies that the complete training process does not use the DPI, so you can safely ignore the warning.

**Comment by Shreeshrii** [comment]
@stweil Do the lstmf files change when different --psm values are used?

**Comment by wrznr** [comment]
@Shreeshrii Most likely not:
```sh
(env) $ tesseract DEWARP_0006_l782.tif DEWARP_0006_l782 --psm 13 --dpi 300 lstm.train
Tesseract Open Source OCR Engine v4.1.0-rc1-223-g3e71 with Leptonica
Page 1
(env) $ ls -l DEWARP_0006_l782.lstmf 
-rw-r--r-- 1 kmw kmw 173 Oct  9 12:50 DEWARP_0006_l782.lstmf
(env) $ tesseract DEWARP_0006_l782.tif DEWARP_0006_l782 --psm 7 --dpi 300 lstm.train
Tesseract Open Source OCR Engine v4.1.0-rc1-223-g3e71 with Leptonica
Page 1
(env) $ ls -l DEWARP_0006_l782.lstmf 
-rw-r--r-- 1 kmw kmw 173 Oct  9 12:50 DEWARP_0006_l782.lstmf
```
