### ISSUE TITLE
What is the status represented by the output traineddata?

### ISSUE THREAD

**Issue by mikylucky** [tesseract-ocr/tesstrain#115]
Hi everyone,
can you tell me if the `.traineddata` generated after the training is representing the coefficients at the last iteration or the coefficients at the iteration with the best CER?

**Comment by stweil** [comment]
You can answer that for yourself. What would make more sense? Using the model from the last iteration, no matter how good or bad it was, or using the model with the lowest CER?

**Comment by mikylucky** [comment]
Lowest CER of course!

But it' better being sure ;)

**Comment by stweil** [comment]
Related: it is also possible to created `traineddata` from the 2nd or 3rd best model. My experience is that the best model is not always the best, but only best on average. Sometimes earlier best models are better. And if you combine the best three models (`-l best+second_best+third_best`), the OCR result can contain the best from three models.

**Comment by stweil** [comment]
OCR results and being sure is a contradiction. :-)
