### ISSUE TITLE
Combining two models

### ISSUE THREAD

**Issue by mikylucky** [tesseract-ocr/tesstrain#116]
Related: it is also possible to created `traineddata` from the 2nd or 3rd best model. My experience is that the best model is not always the best, but only best on average. Sometimes earlier best models are better. And if you combine the best three models (`-l best+second_best+third_best`), the OCR result can contain the best from three models.

_Originally posted by @stweil in https://github.com/tesseract-ocr/tesstrain/issues/115#issuecomment-541656095_

How can I combine two different models?

**Comment by stweil** [comment]
You "combine" them when running Tesseract. Just use the `-l` command line parameter with more than one model as shown in the example above.

**Comment by mikylucky** [comment]
Great, thanks!
