### ISSUE TITLE
Tessdata from specific checkpoint

### ISSUE THREAD

**Issue by mikylucky** [tesseract-ocr/tesstrain#122]
Hi,
is there a way to create a `.traineddata` file from a specific checkpoint?

**Comment by stweil** [comment]
Yes.

**Comment by mikylucky** [comment]
This one?

[](https://github.com/tesseract-ocr/tesseract/wiki/TrainingTesseract-4.00#combining-the-output-files)

**Comment by stweil** [comment]
That's correct. In addition you can use `--convert_to_int`.

**Comment by mikylucky** [comment]
> Yes. I plan to add a Makefile rule which creates `*.traineddata` for all checkpoints.

I'll start working on that now. Do you have any suggestion for the command name?

**Comment by stweil** [comment]
Perhaps `make traineddata`?

**Comment by mikylucky** [comment]
That's exactly what I thought! :D I'll push my modifications right now

**Comment by stweil** [comment]
`make traineddata` now creates best and fast `traineddata` files in two separate directories `tessdata_best` and `tessdata_fast`.

Tesseract can improve the OCR results by using not only the last but the last two or three models (`tesseract ... -l NAME1.traineddata+NAME2.traineddata+NAME3.traineddata`).

**Comment by Shreeshrii** [comment]
@stweil Rather than create traineddata for all checkpoints (which can be in hundreds or more) should they be created only for CER below a certain %?

**Comment by mikylucky** [comment]
@Shreeshrii I'm not very confident this is the best solution.

I'm testing the traineddata from all the checkpoints on an external validation set, and the best training usually is not the one with the lowest CER.

For a 2 million steps training, I get around 100 checkpoints.

We can create a parameter that inserts a treshold in the CER

**Comment by stweil** [comment]
Unfortunately the CER is not clearly separated from the model name which makes parsing of the checkpoint filename more difficult. My longest running training (running for two months now) currently produced 109 checkpoints. Making `traineddata` for those checkpoints was fast. It is also possible to remove unwanted checkpoints before running `make traineddata`. And it should already be possible to pass an explicit list of `CHECKPOINT_FILES` for the generation of `traineddata`. That's why I think the current solution is sufficient.

**Comment by Shreeshrii** [comment]
OK. I checked the number of checkpoints in couple of training run archives and it is indeed less than 100 and not more as I thought.

>We could create a not mandatory parameter that inserts a threshold in the CER though

Good idea, if it is possible to do.

Thanks.

**Comment by stweil** [comment]
Examples which already work:

    # Make traineddata for the checkpoint files of the last three weeks.
    make traineddata CHECKPOINT_FILES="$(find data/foo -name '*.checkpoint' -mtime -21)"

    # Make traineddata for the last two checkpoint files.
    make traineddata CHECKPOINT_FILES="$(ls -t data/foo/checkpoints/*.checkpoint | head -2)"

    # Make traineddata for all checkpoint files with CER better than 1 %.
    make traineddata CHECKPOINT_FILES="$(ls data/foo/checkpoints/*[^1-9]0.*.checkpoint)"

**Comment by Shreeshrii** [comment]
Thank you @stweil, the examples are very helpful.

**Comment by stweil** [comment]
Should I add them to README.md?

**Comment by Shreeshrii** [comment]
Yes, please. That will be great.

**Comment by stweil** [comment]
Could you please have a look at pull request #125?

**Comment by Shreeshrii** [comment]
>Unfortunately the CER is not clearly separated from the model name which makes parsing of the checkpoint filename more difficult (maybe lstmtraining should insert an additional _ separator before the CER).

```
// Returns a suitable filename for a training dump, based on the model_base_,
// best_error_rate_, best learning iteration and training_iteration_.
STRING LSTMTrainer::DumpFilename() const {
  STRING filename;
  filename += model_base_.c_str();
  filename.add_str_double("_", best_error_rate_);
  filename.add_str_int("_", best_iteration_);
  filename.add_str_int("_", training_iteration_);
  filename += ".checkpoint";
  return filename;
}
```

This adds a separator as well as includes the training iteration, e.g. `engPlus_0.251_11_100.checkpoint`.

If that's ok, I will submita PR.

**Comment by mikylucky** [comment]
I think it's a suitable solution that will allow us to be more flexible on `make tessdata`

**Comment by stweil** [comment]
@Shreeshrii, the code looks good. I like the added training iteration.
