### ISSUE TITLE
What is the idea behind "BUILD_TYPE"?

### ISSUE THREAD

**Issue by wrznr** [tesseract-ocr/tesstrain#134]
With https://github.com/tesseract-ocr/tesstrain/commit/480383aeee6f229caecf972b8d4530bcc9584e79 models receive an extra `Plus` when a start model is chosen. @Shreeshrii What is the idea behind this? (I.e. personally, if I set a model name for training I expect my model to have this name after training)

**Comment by Shreeshrii** [comment]
I had added it originally as I had all 4 options for training - scratch, impact, plus and layer, and it allowed using the same set of input files to run different types of training and compare results.

It can be deleted.
