### ISSUE TITLE
List of One Line dataset?? [ Question, not an issue ]

### ISSUE THREAD

**Issue by AyushP123** [tesseract-ocr/tesstrain#138]
Hi,

Thank you for your good work. I wanted to ask if there are any publicly available datasets that you would be aware of which contains single text line in the image.

Thanks and Regards,
Ayush Pandey.

**Comment by wrznr** [comment]
Cf. https://github.com/cneud/ocr-gt for an overview of existing data sets for OCR training with some information on their internal structure.
