### ISSUE TITLE
[Question] Why are .box files generated contain symbols on top of each other?

### ISSUE THREAD

**Issue by Asa-Nisi-Masa** [tesseract-ocr/tesstrain#142]
Hi. It seems that when .box files are generated, all the characters' coordinates are the same. I.e. - the characters are essentially on top of each other. Is this intended, and if so, what am I missing?

**Comment by wrznr** [comment]
It is intended. The coordinates in the box files correspond to the lines which contain the character. Since version 4, Tesseract does not require coordinates on the character level anymore (which makes live a lot easier).

**Comment by Asa-Nisi-Masa** [comment]
> It is intended. The coordinates in the box files correspond to the lines which contain the character. Since version 4, Tesseract does not require coordinates on the character level anymore (which makes life a lot easier).

Thank you for the quick response. One more question: if my problem at hand involes real-world images, does it make sense to train Tesseract on 'messy' real-world images (printed text), or does Tesseract prefer synthetic black-on-white text?

**Comment by wrznr** [comment]
Many people have quite successfully trained Tesseract on images of real printings. Actually, to step beyond synthetic materials was the initial purpose of the tesstrain tools. @stweil has documented his approach in a very detailed form in the [wiki](https://github.com/tesseract-ocr/tesstrain/wiki). I have even trained Tesseract with handwritten text, although the documentation is not yet finished. However, a good preprocessing is helpful (or even necessary).
