### ISSUE TITLE
  make leptonica tesseract ends with error

### ISSUE THREAD

**Issue by sam-kurdi** [tesseract-ocr/tesstrain#150]
i tried to perform below command 
`  make leptonica tesseract`

at the end this error shows up 

> Makefile:307: recipe for target 'tesseract.built' failed
make: *** [tesseract.built] Error 2

**Comment by kba** [comment]
Can you post the actual error message? What OS? Did you install the [dependencies](https://github.com/tesseract-ocr/tesseract/blob/master/INSTALL.GIT.md) etc?

**Comment by mittpy** [comment]
I built Tesseract from source, following this: [link](https://tesseract-ocr.github.io/tessdoc/Compiling.html#linux) 
Make leptonica tesseract did not wok for me.

**Comment by kba** [comment]
> I built Tesseract from source, following this: link

Then why build it again?

Impossible to debug without the error output.

```
Makefile:307: recipe for target 'tesseract.built' failed
make: *** [tesseract.built] Error 2
```

just means that the make process aborted because a process ended with non-zero status. Can you post the compiler output before that?

**Comment by sam-kurdi** [comment]
OS Linux Ubuntu 18.0 on VirtualBox. I build from git, I followed [https://github.com/tesseract-ocr/tesstrain](url) for installation 

after entering this command `make leptonica tesseract` end of the installation is following message 

> Makefile:307: recipe for target 'tesseract.built' failed
make: *** [tesseract.built] Error 2

**Comment by sam-kurdi** [comment]
> I built Tesseract from source, following this: [link](https://tesseract-ocr.github.io/tessdoc/Compiling.html#linux)
> Make leptonica tesseract did not work for me as well.

**dont build it twice**
