### ISSUE TITLE
Error when "training from scratch": Error:Assert failed:in file src/ccstruct/imagedata.cpp, line 644

### ISSUE THREAD

**Issue by mittpy** [tesseract-ocr/tesstrain#154]
Hi, folks, 

Your opinion would be highly appreciated. 
When I train from scratch 400 000 single line images, the training ends up with the following error:

![image](https://user-images.githubusercontent.com/46652501/77822898-8a733980-70ff-11ea-9720-731c64176a18.png)

I run the command: make -r training MODEL_NAME=mnist_400 PSM=7 
For comparison, it is all right when 'fine-tuning'. 

Thank you in advance!

**Comment by Shreeshrii** [comment]
I think this is an open issue with tesseract. Please check issues under
tesseract-ocr/tesseract
