### ISSUE TITLE
Training error

### ISSUE THREAD

**Issue by AlexandeRSaxoN7** [tesseract-ocr/tesstrain#164]
I'm trying to train with images from example
Tesseract 5.0
Leptonica 1.80.0
Error: https://pastebin.com/DdATKMxC

**Comment by stweil** [comment]
The error is reported: `Error: missing ground truth for training`.

So you did not provide enough ground truth (lines) for training. How many lines did you have?

**Comment by AlexandeRSaxoN7** [comment]
Sorry, there were really few images
