### ISSUE TITLE
Tesseract warning

### ISSUE THREAD

**Issue by AlexandeRSaxoN7** [tesseract-ocr/tesstrain#165]
After training, when i am executing tesseract i got warning Failed to load any lstm-specific dictionaries for lang test!! How can i disable this warning or fix it? P.s i used all oem modes

**Comment by stweil** [comment]
Please don't open new issues for each of your new questions and try to find the answer yourself before using the time of others.

Newly trained models don't include a dictionary unless you add one. So add a dictionary to silence the warning or just ignore it.

**Comment by stweil** [comment]
You may add your questions to https://github.com/tesseract-ocr/tesstrain/wiki/FAQ.

**Comment by AlexandeRSaxoN7** [comment]
> So add a dictionary to silence the warning or just ignore it.

How? I tried this https://stackoverflow.com/questions/9568165/custom-dictionary-for-tesseract but its not help

**Comment by stweil** [comment]
You may add your questions to https://github.com/tesseract-ocr/tesstrain/wiki/FAQ.
