### ISSUE TITLE
Getting rms, word train and delta information

### ISSUE THREAD

**Issue by bharathsivakumar1** [tesseract-ocr/tesstrain#173]
So I have been using the tesstrain repository successfully for a while now. I just wanted to know if it possible for me to extract the rms, word_train and delta information that I see at each checkpoint during training, after the training has been fully completed, at each instance at which the checkpoint is written?

**Comment by kba** [comment]
You're probably best off logging to a file with `tee`: `make [...] | tee training.log`.
