### ISSUE TITLE
Failed to read boxes from.. Error during processing.

### ISSUE THREAD

**Issue by filippesic** [tesseract-ocr/tesstrain#179]
Hello,

I read a lot of old posts for training issues and I can't seem to figure it one out. Somehow I always run into the same problem, no matter whether I'm on WSL2 Ubuntu, VirtualBox Ubuntu or native Ubuntu, no matter the Tesseract version. I'm getting a bit desperate. I'm getting kinda the same error from another script. Any help is highly appreciated. I'll provide any additional info if needed.

https://imgur.com/a/gBbl72X

edit: okay i'm just dumb, i can't have empty .gt.txt files ..

**Comment by kba** [comment]
Glad you solved the problem :) You reference https://github.com/UYousafzai/easy_train_tesseract/tree/customdata, I did not know about that project, so linking here for posterity.

**Comment by filippesic** [comment]
Well I'm glad that my embarrassment was useful somehow hah. :)
