### ISSUE TITLE
make training unable to download.

### ISSUE THREAD

**Issue by krautmasker** [tesseract-ocr/tesstrain#197]
Hi guys! I am trying to train some tif files with gt.txt of each. I got every tool needed installed. I got leptonica installed tesseract installed but I figured maybe "make leptonica tesseract" loads them into some folder that it can access so I tried deleting and installing them. Then, I got his error here from terminal:

`wget 'http://www.leptonica.org/source/leptonica-1.80.0.tar.gz'
make: wget: No such file or directory
make: *** [leptonica-1.80.0.tar.gz] Error 1`
After this I was like, any who I can just install tesseract and leptonica and move on with my life. So, running "make training" resulted in this error:

`Failed to read data from: data/foo/all-gt
ICU ERROR: U_FILE_ACCESS_ERROR
make: *** [data/foo/unicharset] Error 4`

I got my training files in data/foo-ground-truth

Thank you!

**Comment by stweil** [comment]
If make tells you that `wget` is missing, it might be a good idea to install that.

**Comment by krautmasker** [comment]
Thank you! I installed wget and it works great now. But, it kinda had nothing to do with the actual error I am getting, which is:

`unicharset_extractor --output_unicharset "data/foo/unicharset" --norm_mode 2 "data/foo/all-gt"
Failed to read data from: data/foo/all-gt
ICU ERROR: U_FILE_ACCESS_ERROR
make: *** [data/foo/unicharset] Error 4`

I am truly clueless...
