### ISSUE TITLE
Same duration for training even if CORES count is changed

### ISSUE THREAD

**Issue by prasad01dalavi** [tesseract-ocr/tesstrain#201]
Default CORES are 4
I have set to `time make training CORES=10 MODEL_NAME=eng_foo1_test`
and tried to get time and also for 
`time make training CORES=2 MODEL_NAME=eng_foo1_test`
both are same

Also tried with following 
`OMP_THREAD_LIMIT=1 time make training CORES=2 MODEL_NAME=eng_foo1_test
`

Still, the there is no improvement in timing.

My System has 12 CORES

**Comment by Shreeshrii** [comment]
See https://github.com/tesseract-ocr/tesstrain/blob/master/Makefile#L40

```
# No of cores to use for compiling leptonica/tesseract. Default: $(CORES)
CORES = 4
```

It is used only while building tesseract and leptonica.

**Comment by prasad01dalavi** [comment]
Yes, I know that. I am assuming that it is for parallely process the training samples. Does that mean, while training at every epoch, these core will not be used? Where and what exactly compiling leptonica/tesseract means?

**Comment by wrznr** [comment]
Unless you disable parallelization explicitly via `OMP_THREAD_LIMIT=1`, Tesseract will make use of all existing cores automatically (Open MP is used). So there isn't much you can do to increase training speed. However, you can always use make's `-j` parameter to parallelize the preparation of the box and lstmf files.
