### ISSUE TITLE
Couldn't load any language!

### ISSUE THREAD

**Issue by derm1ch1** [tesseract-ocr/tesstrain#204]
Hey,
I've trained my custom-language with the given script and it worked out-of-the-box like a charm! :-)

**Anyway I face a crucial problem:**
I got my .traineddata file as an output from training. I copied (just) this file into my tessdata folder.
When I hit the command `tesseract --list-lang` it prints all languages, including my custom `lang.traineddata` file.

But when I try to **use** my custom trained language as in `tesseract img.jpg -l lang stdout` it fails and says: `couldn't load any language!`

All other languages, like _eng_, _deu_ etc. work fine! It's just my custom trained language. 
The Tesseract version I'm using is `4.0.0-beta1` - should I may update my Tesseract?

**What am I doing wrong? :-(**
I would love any answers, suggestions and ideas, since I'm pretty new (24h in) to Tesseract and don't find any working answers on the internet.
Thank you so much and have a great day!

Michael

**Comment by Shreeshrii** [comment]
Please update tesseract and try.

**Comment by stweil** [comment]
> `tesseract img.jpg -l lang stdout`

That's the wrong order. Please try `tesseract img.jpg  stdout -l lang`.

**Comment by derm1ch1** [comment]
Hey guys, thanks for the fast replies!!
I was busy the whole day updating tesseract. Originally I used `sudo apt-get install tesseract-ocr` which results in version 4.0.0-beta1 - and there seems no way to update it?

--> So i cloned the github repository and installed it with the given make files.
 
**Result:**
I now use `tesseract 4.1.1` and the correct syntax `tesseract img.jpg stdout -l lang`.
`tesseract --version` --> 4.1.1
`tesseract --list-langs` --> eng, custom

It still doesn't work - but I get a new error:
```
tesseract (legacy) engine requested but components are not present
Failed loading language 'custom'
Tesseract couldn't load any languages!
Could not initialize tesseract.
```

Do you guys have any idea what's going on and why? 

Thanks a lot and have a good day!!

**Comment by stweil** [comment]
Please use the [Tesseract user forum](https://groups.google.com/d/forum/tesseract-ocr) for further questions.
