### ISSUE TITLE
Error make: *** No rule to make target 'data/ben-ground-truth/20-019.lstmf', needed by 'data/ben/all-lstmf' during training

### ISSUE THREAD

**Issue by srdg** [tesseract-ocr/tesstrain#220]
I have been trying to fine-tune the existing `ben.traineddata` model to suit my use-case but somehow this particular error keeps popping up:  
```
 find data/ben-ground-truth -name '*.gt.txt' | xargs cat | sort | uniq > "data/ben/all-gt"
unicharset_extractor --output_unicharset "data/ben/unicharset" --norm_mode 2 "data/ben/all-gt"
Bad box coordinates in boxfile string! 
Extracting unicharset from plain text file data/ben/all-gt
Wrote unicharset file data/ben/unicharset
make: *** No rule to make target 'data/ben-ground-truth/20-019.lstmf', needed by 'data/ben/all-lstmf'.  Stop.
```
I tried to train the data on google colab environment.  
[This bash script](https://raw.githubusercontent.com/srdg/unarchived_ben_tess/main/src/e2ep.sh) highlights the steps I used to train this [data](https://github.com/srdg/unarchived_ben_tess/releases/download/v0.0.2-alpha/data.zip).  
My search results told me that this was an error pertaining to the Makefile but I am not sure exactly what is the fault here. FYI, the flagged file name in the error changes once in a while, so it is not consistent.
Exactly what can be done to fix this issue?

**Comment by Shreeshrii** [comment]
```
:~/tesstrain/data/ben-ground-truth$ ls
10-002.box       12-004.box       14-005.box       16-008.box       18-009.box       20-011.box       22-013.box       24-015.box       26-017.box       28-019.box       30-021.box
10-002.exp0.tif  12-004.exp0.tif  14-005.exp0.tif  16-008.exp0.tif  18-009.exp0.tif  20-011.exp0.tif  22-013.exp0.tif  24-015.exp0.tif  26-017.exp0.tif  28-019.exp0.tif  30-021.exp0.tif

```

Your naming of tif and gt.txt files does not match. Fix by removing `exp0.` from the tif file names.

Then train with the following (name TESSDATA dir as per your environment(.

```
nohup make lists MODEL_NAME=ben RATIO_TRAIN=0.80 LANG_TYPE=Indic  DEBUG_INTERVAL=-1 TESSDATA=$HOME/tessdata_best MAX_ITERATIONS=99999999 START_MODEL=ben   > data/ben.log &
```

**Comment by Shreeshrii** [comment]
29-026.gt.txt is empty so creates a box file of zero size. Fix the ground truth file.

**Comment by srdg** [comment]
@Shreeshrii thank you for all your help! I wrote the text corpus manually and then used a python script to split into several gt.txt files - looks like I had somehow deleted one line and put an empty newline character in it. I am able to run the training. Again, thank you! Closing this issue since it is resolved.
