### ISSUE TITLE
lstm training core dumped for INR symbol

### ISSUE THREAD

**Issue by vigneshg10** [tesseract-ocr/tesstrain#232]
@Shreeshrii   - Attempt to create training file with INR symbol ₹ - core dumped

Changed the eng.training_text $ to ₹. Then  using gentrain.sh shell created the lstm files for arial font.
You can see the missing properties for inr ₹ symbol. - error1.png
Then using pbtune tried to fine tune and failed. - error2.png
But when I give iterations 1 instead of 400 then it goes through. - pbtunewithsingle iteration.png
Attached the gentrain and pbtune shell dvripts and also the eng.taining_text file.

![error1](https://user-images.githubusercontent.com/2225978/106421363-94359e00-6482-11eb-9e35-b8c51347cc7f.PNG)
![error2](https://user-images.githubusercontent.com/2225978/106421367-9566cb00-6482-11eb-9f12-a2c2085adc79.PNG)

![pbtunewithsingle iteration](https://user-images.githubusercontent.com/2225978/106421374-97308e80-6482-11eb-8318-2791d20df9d7.PNG)

[atttachment.zip](https://github.com/tesseract-ocr/tesstrain/files/5902180/atttachment.zip)

**Comment by Shreeshrii** [comment]
Training with tesstrain.sh is not supported here. Use the python scripts provided in this repo.

Apply the PR https://github.com/tesseract-ocr/tesstrain/pull/230 which has a script to run training for engINR also. See the attached log files from the finetuning run.

[engINR.log1.txt](https://github.com/tesseract-ocr/tesstrain/files/5912741/engINR.log1.txt)

[engINR.log.txt](https://github.com/tesseract-ocr/tesstrain/files/5912744/engINR.log.txt)

[engINR_0.110_287_1900.traineddata.zip](https://github.com/tesseract-ocr/tesstrain/files/5912752/engINR_0.110_287_1900.eval.zip)
