### ISSUE TITLE
The Simple Start Training Command is not working

### ISSUE THREAD

**Issue by YKembal** [tesseract-ocr/tesstrain#234]
I was trying to run the simple "make training" command as below after extracting  "ocrd-testset.zip" to "./data/foo-ground-truth" as shown below , it gives me this error and i don't know what i have done wrong.
![1](https://user-images.githubusercontent.com/47929576/107933882-ffee2f80-6f87-11eb-99a3-4d6f5522b50a.PNG)
![2](https://user-images.githubusercontent.com/47929576/107933885-011f5c80-6f88-11eb-9a5a-b7130c109006.PNG)

**Comment by kba** [comment]
The commands in the Makefile are executed with `cmd.exe`, you need a POSIX shell like `bash`. Can you run this in a Linux VM, in WSL, Cygwin or similar? There is a [windows port of tesstrain](https://github.com/tesseract-ocr/tesstrain/issues/212) if none of these are options.
