### ISSUE TITLE
./plot/plot_cer.sh is missing!

### ISSUE THREAD

**Issue by akmalkady** [tesseract-ocr/tesstrain#239]
Hi!

In the main tutorial it mentioed to plot we need to run the following:
cd ./plot
./plot_cer.sh

However, plot_cer.sh is missing! There is a python file which is plot_cer.py. This file accept only a .csv file.

**Comment by Shreeshrii** [comment]
See https://github.com/tesseract-ocr/tesstrain/tree/ee5f0d33ef96bc51a00a3452cb1c818a910bbff6 for the original version of plotting scripts.

A new proposed version is in the PR https://github.com/tesseract-ocr/tesstrain/pull/236

The csv/tsv files are extracted from the training log.
