### ISSUE TITLE
Add PAGE-XML input functionalities

### ISSUE THREAD

**Issue by wrznr** [tesseract-ocr/tesstrain#24]
Ground Truth within OCR-D is mainly represented in [PAGE XML](https://github.com/PRImA-Research-Lab/PAGE-XML). Training based on input files in this format is highly desirable.

**Comment by bertsky** [comment]
Maybe your [page2img](https://github.com/OCR-D/format-converters/blob/master/page2img.py) is a start. 

For the full depth of PAGE-XML annotation …
- strictly `TextLine`
- polygon (not just bounding box) cropping
- rotating by `@orientation` from deskewing
- including `AlternativeImage` for binarization etc,

… we need something more elaborate though, based on OCR-D/core. Something along the lines of [extract-gt](https://github.com/OCR-D/ocrd_segment/pull/11), but for textlines. We could make that tool permanent, giving the desired hierarchy level (region/line/word) as parameter. This yields a directory structure with filename suffixes that can easily be fed into tesstrain.

Opinions / other options?

**Comment by wrznr** [comment]
> we need something more elaborate though, based on OCR-D/core

Granted. However, I am not sure whether I'd like to see a dependency to OCR-D/core in this repo. I think we should keep things small here and implement an OCR-D processor elsewhere. Let's close this one.

**Comment by bertsky** [comment]
But your page2img is standalone, and could be improved (a little)...

**Comment by wrznr** [comment]
https://github.com/OCR-D/format-converters/pull/9 may help to start with PAGE XML.

**Comment by Shreeshrii** [comment]
Came across a Tool that does layout analysis and/or text recognition using tesseract and outputs the result in Page XML format. Adding here as reference.

https://github.com/mauvilsa/tesseract-recognize
