### ISSUE TITLE
Columns not getting predicted

### ISSUE THREAD

**Issue by Vishal-Mendekar** [tesseract-ocr/tesstrain#251]
Here is the image. I have created line data of all such 10,000 images using the HORC model and used it to train the tesstrain model. 

But now when I am doing prediction on the image the numbers from the first columns are not being predicted at all. What should I do?

![unknown_page_3](https://user-images.githubusercontent.com/54699229/119952306-7f918e80-bfba-11eb-884f-7b84e796c817.jpg) @Shreeshrii @stweil

**Comment by wrznr** [comment]
This seems to be a segmentation issue rather than a training issue. Could you post a line image which you use with your trained model?
