### ISSUE TITLE
I get "Failed to load any lstm-specific dictionaries for lang ea!!" when predicting with fintuned model

### ISSUE THREAD

**Issue by soufieneghribi** [tesseract-ocr/tesstrain#252]
I am trying to finetune a model with a hundreds of images. 
I am using the **ara** model as the **START_MODEL** running this command:
`make training MODEL_NAME=ea START_MODEL=ara TESSDATA=data/ara`

The new model is supposed to perform better than the base model (ara). But I am getting bad results
Example:

![image](https://user-images.githubusercontent.com/26394060/120169669-18611d80-c1f8-11eb-83ac-fcbd7623185e.png)

With ara best model I get:
بن عثمان بِن الهادي _

with the finetuned model I get:
ﻦﻴﻣﺟﺟﺟﺟ_ﺎﻟﺒﻟﻤﻟﻟﺍﻣ

**Comment by wrznr** [comment]
Two very different things in one issue.

> Failed to load any lstm-specific dictionaries for lang ea

This expected since dictionaries are not carried over to the finetuned model (on purpose). Using dictionaries is not recommended in general for LSTM-based OCR.

> The new model is supposed to perform better than the base model

Not necessarily. This very much depends on your training and especially on the images you feed into it. Your example has a very bad line segmentation. Are you using PSM=7 or PSM=13?

**Comment by soufieneghribi** [comment]
> This expected since dictionaries are not carried over to the finetuned model (on purpose). Using dictionaries is not recommended in general for LSTM-based OCR.

Thank you for your response. I'm not using dictionaries, IS this acceptable as a warning? Could it affect my trained model?

> Not necessarily. This very much depends on your training and especially on the images you feed into it. Your example has a very bad line segmentation. Are you using PSM=7 or PSM=13?

I am using PSM=13 for the training and prediciton.

**Comment by wrznr** [comment]
> Thank you for your response. I'm not using dictionaries, IS this acceptable as a warning? Could it affect my trained model?

Yes. Definitely. No worries.

**Comment by soufieneghribi** [comment]
I followed the [documentation ](https://github.com/tesseract-ocr/tesstrain). I prepared 350 one line Arabic images (xx.png) and their transcript (xx.gt.txt) and starting training with START_MODEL=ara. 

>  make training MODEL_NAME=elda START_MODEL=ara TESSDATA=data/ara_best

![image](https://user-images.githubusercontent.com/26394060/120768970-92551780-c514-11eb-974e-81b11a289d78.png)

I am getting 100% as error rate. 

![aa](https://user-images.githubusercontent.com/26394060/120768545-2d99bd00-c514-11eb-916c-79f2a18063ef.PNG)

I there something I am missing?

**Comment by wrznr** [comment]
What is `ara_best`? The `TESSDATA` parameter should direct to your Tesseract model directory (e.g. `/usr/local/share/tessdata` in most cases).
