### ISSUE TITLE
how to apply Transfer Learning while training.So basically i want to continue training on my custom data with  eng.traineddata as base model. how can i do so please help i am a  new user .

### ISSUE THREAD

**Issue by KnitVikas** [tesseract-ocr/tesstrain#253]
Thanks in advance for helping,

**Comment by kba** [comment]
Have a look at https://github.com/tesseract-ocr/tesstrain/wiki/GT4HistOCR

**Comment by bertsky** [comment]
TL in the finetuning regime is supported by tesstrain out of the box: simply set `START_MODEL=eng`.

If instead you want to fixate layers and add more heads, you need to call lstmtraining yourself and read up on [its documentation](https://tesseract-ocr.github.io/tessdoc/tess4/TrainingTesseract-4.00.html#training-just-a-few-layers).

Can we close?
