### ISSUE TITLE
make: *** [tesseract.built] Error 2

### ISSUE THREAD

**Issue by TJUXJH** [tesseract-ocr/tesstrain#265]
[log.txt](https://github.com/tesseract-ocr/tesstrain/files/6661897/log.txt)
hello, I use latest Makefile with commad :  make leptonica tesseract.
however, it failed with "make: *** [tesseract.built] Error 2".
The full is attach to this issue.

**Comment by wrznr** [comment]
@TJUXJH This a tesseract build problem not a tesstrain issue. Pls. get in touch with the Tesseract user group.
