### ISSUE TITLE
MAX_ITERATIONS stopping at 10k even after explicitly supplying using MAX_ITERATIONS argument at 50k

### ISSUE THREAD

**Issue by sajalroychowdhury** [tesseract-ocr/tesstrain#266]
MAX_ITERATIONS stopping at 10k even after explicitly supplying using MAX_ITERATIONS argument at 50k

**Comment by bertsky** [comment]
That's because there's a second criterion for termination: `TARGET_ERROR_RATE` – see README.

If you want the training to ignore that, just set it to zero.

**Comment by whisere** [comment]
Thanks. I understand the TARGET_ERROR_RATE can overwrite MAX_ITERATIONS, and setting MAX_ITERATIONS to 0 to ignore. I am also concerned about overtraining, is there a way to figure out optimal MAX_ITERATIONS? Thanks.
