### ISSUE TITLE
lstm training not working for tesseract 5: 

### ISSUE THREAD

**Issue by wthompson-dascena-analytics** [tesseract-ocr/tesstrain#268]
My goal is to fine-tune the eng.traineddata model to recognize weird codes like "N043.39" and "I34.45". However, I'm getting a strange error.

____________________________________________________________________________

make training START_MODEL="foo-lstm" GROUND_TRUTH_DIR="./data/foo-ground-truth"
lstmtraining \
	  --debug_interval 0 \
	  --traineddata data/foo/foo.traineddata \
	  --old_traineddata /Users/wjtho/tesseract/tesstrain/usr/share/tessdata/foo-lstm.traineddata \
	  --continue_from data/foo-lstm/foo.lstm \
	  --learning_rate 0.0001 \
	  --model_output data/foo/checkpoints/foo \
	  --train_listfile data/foo/list.train \
	  --eval_listfile data/foo/list.eval \
	  --max_iterations 10000 \
	  --target_error_rate 0.01
Loaded file data/foo-lstm/foo.lstm, unpacking...
**Warning: LSTMTrainer deserialized an LSTMRecognizer!
Code range changed from 111 to 32!
old_mgr.Init(old_traineddata):Error:Assert failed:in file src/training/unicharset/lstmtrainer.cpp, line 119
make: *** [data/foo/checkpoints/foo_checkpoint] Abort trap: 6**

______________________________________________________

I'm not sure what this error means. I already made sure that my start model was extracted from the eng.traineddata from tessdata_best. Also, I'm using tesseract 5.0.0-alpha-20210401-145-g767fb.

**Comment by wrznr** [comment]
@wthompson-dascena-analytics I can confirm this problem. Using the current master from the tesseract repo helped to solve this problem in my case (the assert is gone: https://github.com/tesseract-ocr/tesseract/blob/60fd2b4abaa9c5c5c42d32db57576bc95d28a78a/src/training/unicharset/lstmtrainer.cpp#L119). Could you please try whether it works for you too?

**Comment by stweil** [comment]
@wrznr, I am afraid the assertion moved to line 123.
