### ISSUE TITLE
What is the effect of changing the scope of the training text?

### ISSUE THREAD

**Issue by akmalkady** [tesseract-ocr/tesstrain#271]
Hi,

I am trying to follow the TessTutorial to train tesseract from scratch. I have some questions regarding the lang data to understand how the training is working.

The provided training text has some random English words. The questions regarding the training text:

1- Is using text from some scope will improve the performance of tesseract on that scope? For example, training tesseract on special names or vocabs that are not English but has Latin letters and numbers (a-z A-Z 0-9 and special chars). Example: pH_scale1

2 - Is generating words from random letters will do the same as using English words?
The provided eng.trainingtext has text such as :
"different New Articles page 23 a To Service ~~ a details DC that don't as 7 «« Date:"

What if I use something random like this:
"sqwrLwU2bo BLiRDhvAoM USyWtpBFi5 UwLgXyoz1e UqiXudhrhz dDKAdnI8Z2 YIl6T6d7m6 G2IVtTRbuu Lh6NvWNLc3 CGD2SXOoNT"
 
3- I would like to add one more question, were the other Latin languages, such as French trained from scratch or just fine-tuned the English language?

Thanks

https://groups.google.com/g/tesseract-ocr/c/iDqtkzAthA8

**Comment by amitdo** [comment]
>Is generating words from random letters will do the same as using English words?
The provided eng.trainingtext has text such as :
"different New Articles page 23 a To Service ~~ a details DC that don't as 7 «« Date:"
>
>What if I use something random like this:
"sqwrLwU2bo BLiRDhvAoM USyWtpBFi5 UwLgXyoz1e UqiXudhrhz dDKAdnI8Z2 YIl6T6d7m6 G2IVtTRbuu Lh6NvWNLc3 CGD2SXOoNT"

It depends on the text in the images you want to OCR. If you train with random sequences of letters and your text is (mostly) normal sequences of English words, I expect a negative impact.

>were the other Latin languages, such as French trained from scratch or just fine-tuned the English language?

Nobody of us trained the original Latin based languages. AFAIK each language was trained separately.

**Comment by akmalkady** [comment]
I read the Ray's comment regarding the training text. 

> For Latin-based languages, the existing model data provided has been trained on about 400000 textlines spanning about 4500 fonts.

> However much or little corpus text there is, the rendering process makes
50000 chunks of 50 words to render in a different combination of font and
random degradation, which results in 400,000-800,000 rendered textlines.

Let's assume he used 400k lines for 4500 fonts. So for each font would be 89 lines (400,000 / 4500 = 89 lines for each font.)

I am trying to understand how the LSTM training works on Tesseract. Is the training done based on single characters or a character with its adjacent characters or whole words. I don't think 89 lines are enough for whole words. For the first and second cases, I believe random characters would perform the same as using English words.

Another point, if tesseract is just training on the shape of the characters, then fine-tuning the English with the five diacritics and two orthographic ligatures would be enough for the French language.

Is there any good source to explain how the training on LSTM tesseract is exactly working?
