### ISSUE TITLE
Does not create lstmf file: Compute CTC targets failed!

### ISSUE THREAD

**Issue by townim-faisal** [tesseract-ocr/tesstrain#273]
I have tried to train this bengali [data](https://github.com/tesseract-ocr/tesstrain/files/6950314/ben-ground-truth.zip). 

I have run this command:
`make training MODEL_NAME=ben RATIO_TRAIN=0.90 LANG_TYPE=Indic TESSDATA=/mnt/c/T.Faisal/OFFICE/tesstrain START_MODEL=ben GROUND_TRUTH_DIR=data/ben-ground-truth DATA_DIR=data`

I have used the best traineddata from [here](https://github.com/tesseract-ocr/tessdata_best/blob/master/ben.traineddata).

But it does not generate lstmf file in `ben-ground-truth` folder for all images like an example _1461359216_fathers_name_info.png_ in data. It also gives `Normalization failed for string`. You can check here: [ben-ground-truth.zip](https://github.com/tesseract-ocr/tesstrain/files/6950316/ben-ground-truth.zip)

And it gives the following [output](https://github.com/tesseract-ocr/tesstrain/files/6950365/ben.log).

**Comment by kba** [comment]
It's very little data and it isn't properly segmented. IIUC you have just seven images in the data and of those, some are two lines (e.g. 1002509501_address_info.png) or even three lines (e.g. 1009113257_address_info.png).

So I suggest you get some more data and make sure that the image-ground-truth pairs are only a single line.

**Comment by townim-faisal** [comment]
Thank you for your reply @kba. Can you describe to me what do you mean by "it isn't properly segmented"?

**Comment by kba** [comment]
tesstrain (and every modern trainable OCR engine) is trained on line-wise image/text ground-truth. As I said, you have multi-line images in there, that should be split into individual lines. @stefanCCS had [a similar issue](https://github.com/tesseract-ocr/tesstrain/issues/210).

**Comment by townim-bs23** [comment]
Thanks @kba for your help. I am closing this issue

**Comment by townim-faisal** [comment]
Thanks @kba for your help. I am closing this issue.
