### ISSUE TITLE
make training hung

### ISSUE THREAD

**Issue by NeilduToit13** [tesseract-ocr/tesstrain#277]
I got as far as this part of the documentation:
"The repository contains a ZIP archive with sample ground truth, see ocrd-testset.zip. Extract it to ./data/foo-ground-truth and run make training."
After unzipping and running make training my terminal displayed this:
$ make training
unicharset_extractor --output_unicharset "data/foo/unicharset" --norm_mode 2 "data/foo/all-gt
for the next 36 hours. At which point I killed it. No logging at all.
What is this doing and how long is it supposed to take?

**Comment by aquino-a** [comment]
When it is training it will leave logs regularly. No logs for 36 hours is not normal

**Comment by stweil** [comment]
@NeilduToit13, could you please try to run `unicharset_extractor --output_unicharset "data/foo/unicharset" --norm_mode 2 "data/foo/all-gt` directly from the command line instead of running `make training`? Does it terminate then?
