### ISSUE TITLE
radical-stroke.txt location changed

### ISSUE THREAD

**Issue by aquino-a** [tesseract-ocr/tesstrain#278]
It looks like 'master' was changed to 'main' the tesseract project.  This breaks line 317 in the MakeFile.

**Comment by NazeemaShaik** [comment]
I am trying to train tesseract on my custom images. But training is getting stop in the middle. It is not able to find radical-stroke.txt in the location(https://github.com/tesseract-ocr/langdata_lstm/raw/master/radical-stroke.txt). Can anyone help me how to proceed?. Thanks

**Comment by aquino-a** [comment]
The last commit in the `tesseract` project changed 'master' to 'main', which broke all URLs using that branch.

**Comment by stweil** [comment]
This is fixed now. But we should not use the default branch here. Using the latest tagged release would be better.

So please keep this issue open until release 5.0.0 was tagged. Then we can use that.

**Comment by NazeemaShaik** [comment]
![image](https://user-images.githubusercontent.com/47341508/133198900-c849ea0b-ac99-4065-b6fb-38042644915d.png)

I have edited line 317 in makefile as https://github.com/tesseract-ocr/langdata_lstm/raw/main/radical-stroke.txt . But getting the above error. Can you please help me on this?. Thanks

**Comment by stweil** [comment]
That's unrelated to the issue here. The latest Tesseract code would have shown why your training does not work: you start it with a "fast" model instead of using a "best" model.
