### ISSUE TITLE
error during training ( make: * [data/foo/foo.traineddata] Error)

### ISSUE THREAD

**Issue by nebiyebln** [tesseract-ocr/tesstrain#279]
Hi, I created everything correctly. After the 'make training' command, some of my files were not created and I am getting this error:
Config file is optional, continuing...
Failed to read data from: data//foo/foo.config
Failed to read data from: data//radical-stroke.txt
Error reading radical code table data//radical-stroke.txt
Makefile:123: recipe for target 'data/foo/foo.traineddata' failed
make: * [data/foo/foo.traineddata] Error
![Screenshot from 2021-09-16 10-31-23](https://user-images.githubusercontent.com/88368651/133569855-02f4b6a8-165d-43aa-9dc0-eaa65977a46c.png)
@kba 
@zdenop 
@jimregan

**Comment by ozlem-atiz** [comment]
oh. yes i have this error . HELP

**Comment by zdenop** [comment]
posting screenshots does not help much. Input data could help more.

>  I created everything correctly.

So why do you get errors like these?
```
Failed to read data from: data//foo/foo.config
Failed to read data from: data//radical-stroke.txt
Error reading radical code table data//radical-stroke.txt
```

**Comment by haideralipf** [comment]
i have this error 
Connecting to github.com
Unable to establish SSL connection.
Makefile:317: recipe for target 'data/radical-stroke.txt' failed

**Comment by huuson235** [comment]
I have this issue too but it resolved. Simply, rm data/radical-stroke.txt to download it, make sure that your internet is good.
