### ISSUE TITLE
Regarding the training data

### ISSUE THREAD

**Issue by SreyaKambhatla** [tesseract-ocr/tesstrain#280]
Hi, I'm new to this field, and I'm learning a lot of new stuff. But I'm quite stuck at the training data part. I've seen how the ocrd test samples with ground truth. I've extracted that data, followed all the steps, and created the trained data. But when I'm trying to create my own data set to train the tesseract with English as my preferred language, I get a lot of errors when trying to train it. I'm not quite sure where I've gone wrong. Can you please tell me how the foo data set was made? It will be really helpful.

**Comment by aquino-a** [comment]
did you read the instructions?
