### ISSUE TITLE
LSTMF file are not getting generated for some part of dataset

### ISSUE THREAD

**Issue by shirish100** [tesseract-ocr/tesstrain#287]
I ve  already trained an OCR model and its recognition seems to be far better than the its base model eng, however the trained model used PSM value of 13. But when the same thing is trained PSM 6 then  for almost 5% of the data the lstmf files are not generated. Can you tell me the cause of it.

**Comment by TheFattestTony** [comment]
Hi. Maybe PSM6 mode has more dificulty than PSM13 when it comes to identify characters at images, therefore the boxes are not built properly.

**Comment by wrznr** [comment]
PSM 13 uses raw, unoptimized data while PSM 6 makes use of tesseract-internal functionality to preprocess the line images. Maybe something is odd with those 5 % which causes Tesseract to fail in preprocessing? Hard to guess without examples.
