### ISSUE TITLE
Invalid github urls

### ISSUE THREAD

**Issue by z-aliakseyeu** [tesseract-ocr/tesstrain#288]
Hello!

During execution encountered the following error:
```
wget -Odata/radical-stroke.txt 'https://github.com/tesseract-ocr/langdata_lstm/raw/master/radical-stroke.txt'

"HTTP request sent, awaiting response... 404 Not Found "
"2021-11-11 07:46:43 ERROR 404: Not Found. "
"make: *** [Makefile:316: data/radical-stroke.txt] Error 8 "
"FAILED "
"+ RESULT=2 "
"+ '[' 2 -eq 0 ']' "
"+ echo FAILED "
"+ exit 2 "
```

The root cause are the changes been provided to github url mappings and right now the address to raw content is through raw.github.com.

Affected lines:
https://github.com/tesseract-ocr/tesstrain/blob/main/Makefile#L317
https://github.com/tesseract-ocr/tesstrain/blob/main/Makefile#L356

**Comment by stweil** [comment]
The old URL still works for me, but is redirected.
