### ISSUE TITLE
Create and integrate a fancy logo tesstrain

### ISSUE THREAD

**Issue by wrznr** [tesseract-ocr/tesstrain#29]
E.g. https://www.flickr.com/photos/sdasmarchives/27078655499

**Comment by kba** [comment]
![tesseract-train - small](https://user-images.githubusercontent.com/273367/45441277-ecf01a80-b6be-11e8-8c4c-45c44dc9d441.png)

**Comment by ehrmn** [comment]
![ocrd_train](https://user-images.githubusercontent.com/30501577/47211240-4b32ac00-d395-11e8-81f6-e8aa8d6235fd.png)

**Comment by wrznr** [comment]
Nice! I like the barbell. Maybe we could have a smaller more logoish
version in addition (i.e. only the OCR-D logo above and a single T below
the bar)?

**Comment by ehrmn** [comment]
![ocrd_train_logo-00-02](https://user-images.githubusercontent.com/30501577/47718438-b8bdc280-dc48-11e8-891f-1ba3d3499b92.png)
Draft 2. Still needs some improvement.

**Comment by ehrmn** [comment]
![ocrd_train_logo-00-03](https://user-images.githubusercontent.com/30501577/47719211-c116fd00-dc4a-11e8-9318-9f2a4a9edbda.png)
Using the "negative" space as the T and simplified the barbells (looked weird with the bar)

**Comment by kba** [comment]
It's a clever logo.

I am not sure though we should emphasize OCR-D all that much. This is a Makefile for training tesseract, maybe ~100 SLOC. Branding it like this seems a little conceited to me at the moment. But maybe it can motivate us to work more on this, who knows.

**Comment by ehrmn** [comment]
![ocrd_train_logo-00-04](https://user-images.githubusercontent.com/30501577/47719906-d725bd00-dc4c-11e8-8690-c0eb8157e8d2.png)
so not mentioning ocr-d at all?

**Comment by ehrmn** [comment]
![ocrd_train_logo-00-05](https://user-images.githubusercontent.com/30501577/47724065-30461e80-dc56-11e8-97fd-2226fb6ef194.png)
![ocrd_train_logo-00-05b](https://user-images.githubusercontent.com/30501577/47724071-31774b80-dc56-11e8-8a5c-1c505b952ac7.png)
not mentioning ocr-d at all
