### ISSUE TITLE
Training for fonts?

### ISSUE THREAD

**Issue by orsondmc** [tesseract-ocr/tesstrain#305]
I've seen some outdated docs for training tesseract with specific fonts. 

What's the current way of doing this? Pointers would be appreciated :)

**Comment by Shreeshrii** [comment]
You can try the scripts in https://github.com/Shreeshrii/tess5train-fonts

**Comment by stefan6419846** [comment]
If you want to fine tune a model for a specific font using artificial data, the scripts in https://github.com/tesseract-ocr/tesstrain/tree/main/src/training mostly are a drop-in replacement for the old *tesstrains.h* script.
