### ISSUE TITLE
number of MAX_ITERATIONS

### ISSUE THREAD

**Issue by whisere** [tesseract-ocr/tesstrain#311]
Is this still the case:
https://groups.google.com/g/tesseract-ocr/c/AnMYS98VwiE/m/1PN3mF6PAgAJ
The MAX_ITERATIONS depends on the number lstmf files? If I have 1 millions pairs of images and text ground truth for training from scratch, if I want to cover all of them, should I set MAX_ITERATIONS to 1 millions?  Thanks.

**Comment by stweil** [comment]
Typically you would set `MAX_ITERATIONS` to a multiple of the number of lines used for training.

**Comment by whisere** [comment]
Thanks! so is the multiple epoch: max_iterations = epoch * total number of text lines ?
Are there some suggestions on the optimal multiple or epoch for training from scratch without overtraining? Thank you!

**Comment by whisere** [comment]
If the TARGET_ERROR_RATE can't be reached after training for a long time, is it right to kill the training process and run?:
lstmtraining \
--stop_training \
--continue_from data/eeboecco/checkpoints/eeboecco_checkpoint \
--traineddata data/eeboecco/eeboecco.traineddata \
--model_output data/eeboecco.traineddata &
