### ISSUE TITLE
how to prepare the data for new tessdata images in khmer lang

### ISSUE THREAD

**Issue by mengleang-ngoun** [tesseract-ocr/tesstrain#312]
how to prepare the data for new tessdata images in khmer

**Comment by kba** [comment]
Khmer or Arabic?

In principle, it's the same process for every language, you need pairs of lines images and their transcription. AFAIK Khmer is a left-to-right script with distinct characters, so you basically only need ground truth data and you can train both from scratch or fine-tune the existing Khmer model.
