### ISSUE TITLE
./plot/plot_cer.sh is missing!

### ISSUE THREAD

**Issue by MeilyOeng** [tesseract-ocr/tesstrain#313]
plot_cer.sh file is not created after make training so how to extract plot_cer.csv file from TESSTRAIN.LOG

**Comment by stefan6419846** [comment]
This seems to be a documentation error/migration issue in https://github.com/tesseract-ocr/tesstrain/commit/17dcaad64c5e1aa07c16d04fd5c1dded99f6d1ec. Have you tried using the `plot/plot_cer.py` script, which `plot_cer.sh` has just been a wrapper for?

**Comment by MeilyOeng** [comment]
> This seems to be a documentation error/migration issue in [17dcaad](https://github.com/tesseract-ocr/tesstrain/commit/17dcaad64c5e1aa07c16d04fd5c1dded99f6d1ec). Have you tried using the `plot/plot_cer.py` script, which `plot_cer.sh` has just been a wrapper for?

I have checked it `plot_cer.py` but it is just a plot file that get data from csv file, so basically `plot_cer.sh` extract data from log file into csv file.
