### ISSUE TITLE
Fine-tune the english model

### ISSUE THREAD

**Issue by gabriel-fsa** [tesseract-ocr/tesstrain#324]
I'm trying to improve the English model using images where it made a mistake, changed the by 0, 1 by 7 etc. But I can't, it always gives the following error `Failed to load any lstm-specific dictionaries for lang eng-trained!!`

Is there some extra configuration I need to do in the makefile? or is the current configuration not made to fine-tune an existing model? Thanks

**Comment by zdenop** [comment]
Please provide all steps and data reproducing problem.

**Comment by zdenop** [comment]
Missing details from reporter.
