### ISSUE TITLE
How to train new language

### ISSUE THREAD

**Issue by Erdene-Ochir0417** [tesseract-ocr/tesstrain#329]
Hello 

I'm trying to train tesseract on Mongolian language but it said that "Error opening data file /content/tessdata/eng.traineddata". There is mon.traineddata in /content/tessdata folder.
Is it possible to train with renaming mon.trainneddata to eng.trainneddata?

command:
`make training MODEL_NAME=mon`

mon-ground-truth folder:
0.png
0.gt.txt
......

**Comment by zdenop** [comment]
Read the [documentation](https://tesseract-ocr.github.io/tessdoc/), follow [instructions](https://github.com/tesseract-ocr/tesstrain#tesstrain) and use tesseract user forum for asking questions.
