### ISSUE TITLE
How to optimize the size of traineddata

### ISSUE THREAD

**Issue by Monster-2019** [tesseract-ocr/tesstrain#346]
I use lstmtraining to train some Arabic numerals in the game, and use eng's LSTM model for training, but my final traineddata does not need to recognize eng, I hope to remove the part of traineddata that recognizes eng to optimize the size of traineddata. What should I do?

**Comment by stweil** [comment]
A newly trained model does not contain language specific information like dictionaries. It only contains the neural network and the mapping for the unichars. Please use the [Tesseract user forum](https://groups.google.com/d/forum/tesseract-ocr) for additional questions.
