### ISSUE TITLE
Failed training on both Linux WSL and Windows

### ISSUE THREAD

**Issue by kelvinyee00** [tesseract-ocr/tesstrain#349]
Hi,

I want to train a new font and was initially trying to train on windows purely but I hit a wall on that. I built the tesseract from source and I have also read through the tesstrain README and have as far as I am concerned installed all the prerequisites and place the ground-truth in the correct directory. However, I kept getting the same error over and over. Below is the error i faced in cmd.
![windows](https://github.com/tesseract-ocr/tesstrain/assets/129766978/6498ee03-74be-4477-b4e2-57b7026d1a66)

Here is my directory of the ground-truth folder
![image](https://github.com/tesseract-ocr/tesstrain/assets/129766978/22b7bc0d-27a5-49e2-be73-5db9b2a00b51)

I was lost so i tried out another way which is to use WSL and built everything again from scratch. Unfortunately, the same exact error occurs there as well.  I really don't know how to proceed further. Please someone here please give me some guidance. I would really appreciate it.
![linux](https://github.com/tesseract-ocr/tesstrain/assets/129766978/b0a1d2b6-f737-446a-a6db-8e2752321701)

**Comment by stefan6419846** [comment]
> Unfortunately, the same exact error occurs there as well.

Where do you see the same error? The error on WSL is related to a missing shared object, while the Windows issue is completely different? The other lines are just the actual commands run by the Makefile.

**Comment by kelvinyee00** [comment]
I am sorry I didn't notice they were different errors. That's my bad. Anyways, do you have any suggestions on your side to get it running on both methods if possible. I am keen to know why and how this works. Thank you very much for your replies

**Comment by zdenop** [comment]
Follow instructions on https://github.com/tesseract-ocr/tesstrain/blob/main/README.md with example data, and pay attention to each error (make could fail later after error). If sample data training works, try your data...
