### ISSUE TITLE
Ca not open the eng.trainned data

### ISSUE THREAD

**Issue by MuFazil** [tesseract-ocr/tesstrain#353]
I am trying to train a model on top of the english model. When I run the train command ;It gives the following error.

combine_tessdata -u data/tessdata/eng.traineddata data/eng/foo
Failed to read data/tessdata/eng.traineddata
make: *** [Makefile:156: data/foo/unicharset] Error 1

I have downloaded the eng.traineddata from /tesseract-ocr/tessdata_best/blob/main/eng.traineddata

**Comment by stweil** [comment]
Yes, you [already said so](https://github.com/tesseract-ocr/tesseract/issues/3897#issuecomment-1740871018). Did you check whether the downloaded eng.traineddata is really a traineddata file and not HTML code?

Please use the [Tesseract user forum](https://groups.google.com/d/forum/tesseract-ocr) for questions.
