### ISSUE TITLE
Training a model from scratch with own imgs + txts?

### ISSUE THREAD

**Issue by Waji97** [tesseract-ocr/tesstrain#367]
Hello,

I am a bit confused on how to properly train tesseract with line images and texts. I read somewhere that it's possible, but I find the whole thing really confusing.

Can someone help me out? I just want a simple pipeline to train Tesseract on.
Sorry for such a primitive question, but I don't even know how to get started :(

Any help is highly appreciated!

**Comment by stweil** [comment]
Please use the [Tesseract user forum](https://groups.google.com/d/forum/tesseract-ocr) for questions.
