### ISSUE TITLE
How to train captcha?

### ISSUE THREAD

**Issue by sinall** [tesseract-ocr/tesstrain#385]
I was previously use jTessBoxEditor to generate box files and then train captchas.
I tried this project, I run train using 235 captcha files (each has 4 number).

captcha file:
![0a9f-fd26-be30-3ce8](https://github.com/tesseract-ocr/tesstrain/assets/1246382/abe22e24-2d95-4362-988c-bcf103becfb5)

box file:
[0a9f-fd26-be30-3ce8.box.txt](https://github.com/tesseract-ocr/tesstrain/files/14886100/0a9f-fd26-be30-3ce8.box.txt)

tesseract result:
359130

The result is very wrong. I found all box files were different from files from jTessBoxEditor. Please advice me.

**Comment by zdenop** [comment]
we do not support captcha breaking.

**Comment by sinall** [comment]
> we do not support captcha breaking.

What does that mean, should I generate box files by myself?

**Comment by sinall** [comment]
@zdenop can I write a script to generate box files for captcha files then use all other scripts?

**Comment by ipaqmaster** [comment]
> I was previously use jTessBoxEditor to generate box files and then train captchas. I tried this project, I run train using 235 captcha files (each has 4 number).
> 
> captcha file: ![0a9f-fd26-be30-3ce8](https://private-user-images.githubusercontent.com/1246382/320030299-abe22e24-2d95-4362-988c-bcf103becfb5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI3Mjg0MjYsIm5iZiI6MTcxMjcyODEyNiwicGF0aCI6Ii8xMjQ2MzgyLzMyMDAzMDI5OS1hYmUyMmUyNC0yZDk1LTQzNjItOTg4Yy1iY2YxMDNiZWNmYjUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDQxMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA0MTBUMDU0ODQ2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YzkxOTg0MTBlMTUyZTUxMzA3MWFlYjE0M2JmMmUyY2I4Mzc2NDc3MDNmYzQxOTBlNzJhMWUyODUxNGQ4MThhZiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.9YWaeyes_LbYmjPrvucOZFBtw4k6duEDDVP6buPJeN4)
> 
> box file: [0a9f-fd26-be30-3ce8.box.txt](https://github.com/tesseract-ocr/tesstrain/files/14886100/0a9f-fd26-be30-3ce8.box.txt)
> 
> tesseract result: 359130
> 
> The result is very wrong. I found all box files were different from files from jTessBoxEditor. Please advice me.

Tesseract as it currently is had zero problem extracting 4830 from that picture from my screenshot just now.
