### ISSUE TITLE
winget install GnuWin32.Make error

### ISSUE THREAD

**Issue by Roboxkin** [tesseract-ocr/tesstrain#386]
```
winget install wingetcreate
Found Windows Package Manager Manifest Creator [Microsoft.WingetCreate] Version 1.6.1.0
This application is licensed to you by the owner.
Microsoft is not responsible for and does not provide any licenses for third-party packages.
Installer hash verified successfully
Starting package installation...
   ██████████████████████████████ 100%
Installed successfully
```
```
winget install GnuWin32.Make
No packages were found that match the entered conditions.
```
What am I doing wrong?
Thank you

**Comment by zdenop** [comment]
This is not tesseract issue.

**Comment by Roboxkin** [comment]
> This is not tesseract issue.

Why did you close the problem?
It's not resolved

I followed the instructions that you wrote yourself and I want to get a clear answer to my question

![Screenshot](https://github.com/tesseract-ocr/tesstrain/assets/39112555/beddcaa2-749a-41f4-8ff0-1a1753230479)

**Comment by stweil** [comment]
That's the README for tesstrain, so it is a tesstrain issue. I'll move it ...

**Comment by stweil** [comment]
@Roboxkin, posting screenshots not only wastes a lot of resources because images are much larger than text, but are also not useful in this case. It would have been easier for me if you had written that the instructions which failed for you were documented in the README of tesstrain.

**Comment by zdenop** [comment]
winget states it provided this package: https://winget.run/pkg/GnuWin32/Make
Raise issue at winget if not or download and install it manually.

**Comment by stweil** [comment]
Microsoft removed `GnuWin32.Make` in February (see https://github.com/microsoft/winget-pkgs/pull/140010). It was replaced by `ezwinports.make`, so try to install that package.

**Comment by Roboxkin** [comment]
Thank you very much for your answers!
It's very valuable

**Comment by Roboxkin** [comment]
```
winget install ezwinports.make
Found ezwinports: make [ezwinports.make] Version 4.4.1
This application is licensed to you by the owner.
Microsoft is not responsible for and does not provide any licenses for third-party packages.
Download https://downloads.sourceforge.net/project/ezwinports/make-4.4.1-without-guile-w32-bin.zip
   ██████████████████████████████ 383 KB / 383 KB
Installer hash verified successfully
Extracting the archive...
Archive extracted
Starting package installation...
Path environment variable changed; restart the shell to use the new value.
Added command line alias: "make"
Installed successfully

winget install wget
Found Wget [JernejSimoncic.Wget] Version 1.21.4
This application is licensed to you by the owner.
Microsoft is not responsible for and does not provide any licenses for third-party packages.
Download https://eternallybored.org/misc/wget/1.21.4/64/wget.exe
   ██████████████████████████████ 6.71 MB
Installer hash verified successfully
Starting package installation...
Path environment variable changed; restart the shell to use the new value.
Added command line alias: "wget"
Installed successfully
```

**Comment by Roboxkin** [comment]
Problem solved!
Thank you very much for the help
