### ISSUE TITLE
Can't train tesseract with custom font, getting error `No rule to make target 'data/eft-ground-truth/line_177.lstmf', needed by 'data/eft/all-lstmf'.  Stop.`

### ISSUE THREAD

**Issue by manuelarte** [tesseract-ocr/tesstrain#401]
Hi,

I am using Tesseract for a personal project, and I realised that it fails quite often when guessing the text from my image. I think it's due to the font used.

So I am trying to train tesseract with that font. I created a small project that does the following, base on a multiline input txt file, it creates one tiff image per line [https://github.com/manuelarte/tesstraineft](https://github.com/manuelarte/tesstraineft).

In that github repo you can find the font used. And to create the images I run it with `python3 main.py`. It names the files as tesstrain is expecting it, gt.txt and .tiff.

But then, when I copy those files into the data/eft-ground-truth directory and run 
```
> make training MODEL_NAME=eft
```
I get the following error:
```
gmake: *** No rule to make target 'data/eft-ground-truth/line_106.lstmf', needed by 'data/eft/all-lstmf'.  Stop.
```

Any idea what am I doing wrong? If I follow the readme and exctract the test data dn run it with foo it works, but with my images it does not. 
PS: I attached the images used just in case
 
[data.zip](https://github.com/user-attachments/files/16899738/data.zip)

**Comment by johnlockejrr** [comment]
Delete all old data/eft-ground-truth/*.lstmf file and data/eft/all-lstmf to be regenerated

**Comment by manuelarte** [comment]
@johnlockejrr thanks for your reply. I did it but I still get the same error. And actually, I don't even have any *.lstmf file either in data/eft-ground-truth or data/eft

**Comment by manuelarte** [comment]
Ok, the issue is that the image extensions is tiff, and not tif.

**Comment by manuelarte** [comment]
Hello @johnlockejrr , yes, the reason I am creating this training it's because tesseract confuses @ with 0, and 3 with 5, etc. The text that I want to parse can be in different languages, mainly English. To be honest I am quite new to this, and I am investigating, so the start model thingy can help definitvely.

**Comment by manuelarte** [comment]
As writing, it's generating the checkpoints, thanks for your help @johnlockejrr
