### ISSUE TITLE
Rename

### ISSUE THREAD

**Issue by kba** [tesseract-ocr/tesstrain#48]
... to something with tesseract

**Comment by cneud** [comment]
I guess ``tesstrain`` is the obvious one unless you want to go [Schläfli](https://en.wikipedia.org/wiki/Schl%C3%A4fli_symbol) or similar (``cube`` was already used).

**Comment by wrznr** [comment]
We should do this asap. I already read formulations like

> I trained with ocrd and...

**Comment by stweil** [comment]
Do you want to keep "ocrd" in the name (e. g. `ocrd_tesstrain`)? If not, moving the code to https://github.com/tesseract-ocr might also be an option.

**Comment by kba** [comment]
> Do you want to keep "ocrd" in the name (e. g. ocrd_tesstrain)?

I do not. As @wrznr says, it is misleading here.

>  If not, moving the code to https://github.com/tesseract-ocr might also be an option.

I'd favor that.

**Comment by stweil** [comment]
@zdenop and @Shreeshrii suggest a new repository there (see discussion at the [tesseract-dev forum](https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!topic/tesseract-dev/36HxFdSsQqM)).

I suggest to name it https://github.com/tesseract-ocr/tesstrain.

If that is fine for everybody, @zdenop could create it, and we could transfer the content from `ocrd-train`.

**Comment by stweil** [comment]
An alternate solution would be [transferring the ownership](https://help.github.com/en/articles/transferring-a-repository). That has the advantage that everything is transferred (wiki, issues, stars, ...), but needs (temporarily) modified rights on GitHub.

**Comment by wrznr** [comment]
I guess transferring the repository is much easier than copying the contents. Is it sufficient if add @stweil as an owner to this repo? Or who would be the most logic choice?

**Comment by stweil** [comment]
Maybe any owner of the repository can initiate the transfer to https://github.com/tesseract-ocr. Then @zdenop should get an e-mail giving the option to accept or reject the transfer. If the new owner doesn't accept the transfer within one day, it won't complete (see https://help.github.com/en/articles/transferring-a-repository#about-repository-transfers).

@wrznr or @kba, you can just try that. After having accepted the transfer, @zdenop would still have to rename the repository from `ocrd-train` to `tesstrain`.

**Comment by kba** [comment]
You need permission to create new repositories in the organisation you're transferring to. If I try to transfer to `tesseract-ocr`:

> You don’t have the permission to create repositories on tesseract-ocr

I'll give you owner rights and you can try yourself @stweil

**Comment by stweil** [comment]
I see. For transfers to an organization different rules apply: https://help.github.com/en/articles/transferring-a-repository#repository-transfers-and-organizations.

As I am only a member at `tesseract-ocr` and members are currently not allowed to create new repositories there, I get the same error message when I try a transfer. We need help from @zdenop who must either give me the right to create the new repository or who must be added to the list of owners of the current `ocrd-train`. @zdenop, which variant is easier for you?

**Comment by zdenop** [comment]
@stweil : try now: I changed your role in tesseract organization (for this task)

**Comment by stweil** [comment]
Thank you, @zdenop and all others who were involved in the discussion and process.

The repository is moved and renamed now, so this issue can be closed. We can now consider updating the README, maybe changing the directory structure and moving the training scripts from https://github.com/tesseract-ocr/tesseract/tree/master/src/training to `tesstrain`.

**Comment by Shreeshrii** [comment]
There are many references to ocrd-train in forum posts etc. Is it possible to have a dummy repo which redirects to the new repo? 

Or, does github automatically redirect pages when a repo has been renamed/moved?

**Comment by kba** [comment]
It will automatically redirect.

**Comment by Shreeshrii** [comment]
Great. Thanks!
