### ISSUE TITLE
Normalization Mode

### ISSUE THREAD

**Issue by Shreeshrii** [tesseract-ocr/tesstrain#53]
This is not really an issue with ocrd-train and is regarding the following comment in makefile.

>> Normalization Mode - see src/training/language_specific.sh for details. Default: $(NORM_MODE)

`Norm_modes` are also specified in https://github.com/tesseract-ocr/tesseract/blob/master/src/training/unicharset_extractor.cpp#L103

There is a conflict between the suggested norm_modes in `language_specific.sh` and `unicharset_extractor.cpp`.

I think that `unicharset_extractor.cpp` is correct and will create a PR in tesseract repo for changing `language_specific.sh` . See this [comment for proposed change](https://github.com/tesseract-ocr/tesseract/pull/2244#issuecomment-464275278).

Meanwhile if you want you can change the comment in makefile.

**Comment by wrznr** [comment]
@stweil @kba I am confused. Is there something we can/should do here?
