### ISSUE TITLE
Box file generated with same coordinate while using "make training" command, is it correct?

### ISSUE THREAD

**Issue by 24121987** [tesseract-ocr/tesstrain#88]
Hi,

We are creating dataset, in the dataset we have put image(.jpg) file & text file and then we have using "make training" command for training,
Trasining has been completed successfully, But there is only concern about ".box" file 
Box file had generated same coordinate.

Below attached the zip file (.box & tif file),Please look both of the file. ..box file has all same coordinates..I don't understand is correct or not?  

[files.zip](https://github.com/tesseract-ocr/tesstrain/files/3574440/files.zip)

Below are the .box file coordinates.

H 0 0 348 29
e 0 0 348 29
  0 0 348 29
k 0 0 348 29
n 0 0 348 29
e 0 0 348 29
w 0 0 348 29
  0 0 348 29
t 0 0 348 29
h 0 0 348 29
e 0 0 348 29
  0 0 348 29
r 0 0 348 29
u 0 0 348 29
l 0 0 348 29
e 0 0 348 29
s 0 0 348 29
, 0 0 348 29
  0 0 348 29
h 0 0 348 29
e 0 0 348 29
  0 0 348 29
b 0 0 348 29
r 0 0 348 29
o 0 0 348 29
k 0 0 348 29
e 0 0 348 29
  0 0 348 29
t 0 0 348 29
h 0 0 348 29
e 0 0 348 29
m 0 0 348 29
. 0 0 348 29
	 348 29 349 30

Every file genarting same coordinates using "make training" command..inside the "generate_line_box.py" file is running to generate .box and tif file.

**Comment by kba** [comment]
Yes, that is to be expected. C.f.
https://github.com/tesseract-ocr/tesstrain/issues/25 and 
https://github.com/tesseract-ocr/tesstrain/issues/32 for previous discussions on this.

**Comment by 24121987** [comment]
thanks, i got the answer.

**Comment by 4F2E4A2E** [comment]
Thanks for answering the question @kba, but does anyone know how to fine tune a model if the boxes are being generated for the whole line in v5?
