### ISSUE TITLE
Incremental model training possible in tesseract 4.0?

### ISSUE THREAD

**Issue by 24121987** [tesseract-ocr/tesstrain#92]
Hi,

I have generated one model and combine with default trained model is "eng.traineddata". It mean, I am able to trained model using tesseract 4.0, Now next time while generating or adding new font then we have to use our own custom generated model ( custom model name is "ocrmodel1.1") for training instead of using default "eng.traineddata".

eg. first time generated model using "eng.traineddata" under the folder of tesseract\tessdata\eng.traineddata
Next time while going to trained with same model we will use same eng.traineddata model or own generated model like ocrmodel1.1

is it possible to incremental model into the last generated model or every time using same "eng.traineddata"

Please correct me about re-trained model with other font

**Comment by wrznr** [comment]
I do not understand your question. Sorry. Could you provide the commands you used/want to use?
