### ISSUE TITLE
Make Training resulting in Failed to continue error

### ISSUE THREAD

**Issue by SourEyeglasses** [tesseract-ocr/tesstrain#94]
I am using Tesseract 4.0.0-beta.1. I am attempting OCR on English handwriting and am fine tuning on top of the Eng traineddata. I start training by running the follow command:

_make training MODEL_NAME=eng STEPS=6000_

The I continue training with the following command:

_make training MODEL_NAME=eng STEPS=15000 START_MODEL=eng_

While the training is occurring if I cancel it prior to reaching the max iterations and try to continue training (with the last command) I receive the following error:

_lstmtraining
--traineddata data/eng/eng.traineddate
--old_traineddata /home/ubuntu/ocrd-train/usr/share/tessdata/eng.traineddata
--continue_from data/eng/eng.lstm
--net_spec "[1,36,0,1 Ct3,c,16 Mp3,3 Lfys48 Lfx96 Lrx96 Lfx256 01c'head -n1 data/unicharset']"
--model_output data/checkpoints/eng
--learning_rate 20e-4
--train_listfile data/list.train
--eval_listfile data/list.train
--max_iterations 250000
Failed to continue from: data/eng/eng.lstm
Makefile:131 recipe for target 'data/checkpoints/eng_checkpoint' failed
make: *** [data/checkpoint/eng_checkpoints] Error_

I know the easiest solution is to not cancel training during training, but I have had this situation occur also because of computer issues/connectivity issues and every time I try to pick up where I left off I get the error. The only solution I have found is running make clean and restarting from zero.

I have attempted to delete the newest checkpoint file and starting training with a older checkpoint file using this command:

_make training MODEL_NAME=eng STEPS=6000 continue_from=data/checkpoints/eng1.368_50303.checkpoint_

I would greatly appreciate any help. Thank you.

**Comment by wrznr** [comment]
Tough question. Have not tried to cancel training and continue from the intermediate result. I use the `continue from` mechanism for fine tuning one of the Tesseract stack models. @stweil Any ideas?

**Comment by Shreeshrii** [comment]
@SourEyeglasses I am able to continue from cancelled training using my modified makefile at https://github.com/tesseract-ocr/tesstrain/blob/cf7854cbf2a07013fc3df2bbaddebf719534b27b/Makefile
