### ISSUE TITLE
I got Error, Segmentation fault (core dumped) 

### ISSUE THREAD

**Issue by 24121987** [tesseract-ocr/tesstrain#95]
Hi Team,

Below are the error which I have received.
===================================== ERROR=====================
 Segmentation fault      (core dumped) "${cmd}" "$@" 2>&1
     14044 Done                    | tee -a "${LOG_FILE}"
ERROR: Program tesseract failed. Abort.
generate_training_data.sh: 14: generate_training_data.sh: --my_boxtiff_dir: not found
v2team@v2mumpc0697:~/Documents/Helvetica-tamoha-training$ 

Could you help any one why this error has come?

**Comment by wrznr** [comment]
From the information you provide here it is not possible to judge. You should at least provide the command which caused the error!
