### ISSUE TITLE
ERROR: Program unicharset_extractor failed?

### ISSUE THREAD

**Issue by 24121987** [tesseract-ocr/tesstrain#96]
Hi,

below error received during training.

=== Phase UP: Generating unicharset and unichar properties files ===
/home/v2team/Documents/six_font_training/tesseract/src/training/tesstrain_utils.sh: line 350: /bin/ls: Argument list too long
[Wed Sep 11 21:28:53 IST 2019] /usr/bin/unicharset_extractor --output_unicharset /tmp/eng-2019-09-11.diI/eng.unicharset --norm_mode 1
Usage: /usr/bin/unicharset_extractor [--output_unicharset filename] [--norm_mode mode] box_or_text_file [...]
Where mode means:
 1=combine graphemes (use for Latin and other simple scripts)
 2=split graphemes (use for Indic/Khmer/Myanmar)
 3=pure unicode (use for Arabic/Hebrew/Thai/Tibetan)
Reads box or plain text files to extract the unicharset.
ERROR: Program unicharset_extractor failed. Abort.

Please help me, regarding above error.

**Comment by wrznr** [comment]
The error seems to be with `tesstrain_utils.sh` which receives to many arguments (so it is actually a probelm of your command line). Are you sure you are employing the Makefile which is distributed through this repository? Which instructions do you use for training?
