### ISSUE TITLE
Makefile:213: recipe for target 'tesseract.built' failed

### ISSUE THREAD

**Issue by dotuonglong** [tesseract-ocr/tesstrain#97]
After downloading the repo and install dependencies:
sudo apt-get install g++ # or clang++ (presumably)
sudo apt-get install autoconf automake libtool
sudo apt-get install pkg-config
sudo apt-get install libpng-dev
sudo apt-get install libjpeg8-dev
sudo apt-get install libtiff5-dev
sudo apt-get install zlib1g-dev

sudo apt-get install libicu-dev
sudo apt-get install libpango1.0-dev
sudo apt-get install libcairo2-dev

sudo apt-get install autoconf-archive

running the command:
sudo make leptonica tesseract 
I get the error:
.....
Making install in unittest
make[2]: Entering directory '/home/longdt/Desktop/tesstrain-masterr/tesseract-4.1.0/unittest'
make[3]: Entering directory '/home/longdt/Desktop/tesstrain-masterr/tesseract-4.1.0/unittest'
make[3]: Nothing to be done for 'install-exec-am'.
make[3]: Nothing to be done for 'install-data-am'.
make[3]: Leaving directory '/home/longdt/Desktop/tesstrain-masterr/tesseract-4.1.0/unittest'
make[2]: Leaving directory '/home/longdt/Desktop/tesstrain-masterr/tesseract-4.1.0/unittest'
make[1]: Leaving directory '/home/longdt/Desktop/tesstrain-masterr/tesseract-4.1.0'
Makefile:213: recipe for target 'tesseract.built' failed
make: *** [tesseract.built] Error 2

Please help me, regarding above error.

**Comment by wrznr** [comment]
Please file your issue in the Tesseract repository or even better the Tesseract forum. It is not related to `tesstrain`.

**Comment by RonakDedhiya** [comment]
Got similar error...Any solution to solve this issue

**Comment by wrznr** [comment]
@RonakDedhiya As mentioned above, this is a Tesseract-related issue which is not related to `tesstrain`. Pls. place an issue there.

**Comment by stweil** [comment]
@RonakDedhiya, please use the [Tesseract user forum](https://groups.google.com/d/forum/tesseract-ocr) for questions. Don't use the issues for that.
